@echo off
cd /d E:\OmniMarket-Financial-Monitor
echo 启动 OmniMarket 全自动开发模式...
echo 执行自动问题修复...
powershell -ExecutionPolicy Bypass -File "scripts\auto_fix.ps1" -FixType all
echo 启动开发环境...
powershell -ExecutionPolicy Bypass -File "auto_dev.ps1"
pause
